##################################################################################################
### Script for the manuscript 'The time efficiency gain in sharing and reuse of research data' ###
### by Tessa Pronk, Utrecht University Library, KWR water cycle research institute             ###
###                                                                                            ###
### Specifically, this script produces the barplots of Figure 2 in the manuscript              ###
###                                                                                            ###
### The numbers for these figures were extracted from the matrix 'res_matrix'                  ###
### that is generated by the script 'Fig1DataReuseBenefit.R'                                   ###
### with appropriate parameter settings that represent the scenarios and sharing rates         ###
###                                                                                            ###
### Written by Tessa Pronk January 2019 CC-by                                                  ###
### version after review of the paper by reviewers of the Data science joural                  ###
##################################################################################################



#######################################################
# Make the barplot of minimal reuse in Figure 2
#######################################################


# set the plot window with margins
windows(25,15)
par(mfrow = c(2, 2),mar = c(4.5, 8, 5, 5))

# these numbers below were deducted from the 'res_matrix' 
# in script 'Fig1DataReuseBenefit.R'
# numbers may vary slightly in new simulations because of stochastic effects in the simulation model

mydata1 <- c(0.31,0.63,1.06)
mydata2 <-c(0.13,0.13,0.14)

barplot((mydata1), ylab="Minimum % reuse", beside=TRUE, space=c(0.25,0.25) ,cex.axis=2,cex.lab=2,cex.main=2.5,
        col="orange",ylim=c(0,2),main="Scenario A",cex.names = 2,names.arg=c("25% sharing", "50% sharing", "75% sharing"))
par(new = T)
barplot(as.matrix(mydata2),  ylim=c(0,2),beside=TRUE,space=c(0.25,0.25) ,
        col="red",yaxt="n")
legend(0.5, 1.5, c("papers","datasets"), cex=2, 
       fill=c("orange","red"))

mydata1 <- c(0.39,0.87,1.16)            # these numbers were generated by script 'Fig1DataReuseBenefit.R'
mydata2 <-c(0.16,0.17,0.15)

barplot(as.matrix(mydata1), ylab="Minimum % reuse", beside=TRUE, cex.names = 2,names.arg=c("25% sharing", "50% sharing", "75% sharing"),
        col=c("orange"),ylim=c(0,2),main="Scenario B",cex.axis=2,space=c(0.25,0.25) ,cex.lab=2,cex.main=2.5)
par(new = T)
barplot(as.matrix(mydata2), beside=TRUE, ylim=c(0,2),space=c(0.25,0.25) ,
        col="red",yaxt="n")

mydata1 <- c(4.08,8.6,12.89)            # these numbers were generated by script 'Fig1DataReuseBenefit.R'
mydata2 <-c(1.81,1.83,1.76)

barplot(as.matrix(mydata1), ylab="Minimum % reuse", beside=TRUE,cex.names = 2,names.arg=c("25% sharing", "50% sharing", "75% sharing"), 
        col="orange",ylim=c(0,18), main="Scenario C",cex.axis=2,space=c(0.25,0.25) ,cex.lab=2,cex.main=2.5)
par(new = T)
barplot(as.matrix(mydata2), beside=TRUE, ylim=c(0,18),space=c(0.25,0.25) ,
        col="red",yaxt="n")

mydata1 <- c(4.87,10.77,16.67)            # these numbers were generated by script 'Fig1DataReuseBenefit.R'
mydata2 <-c(2.15,2.31,2.28)

barplot(as.matrix(mydata1), ylab="Minimum % reuse", beside=TRUE, cex.names = 2,names.arg=c("25% sharing", "50% sharing", "75% sharing"),
        col="orange",ylim=c(0,18), main="Scenario D",cex.axis=2,space=c(0.25,0.25) ,cex.lab=2,cex.main=2.5)
par(new = T)
barplot(as.matrix(mydata2), beside=TRUE,ylim=c(0,18),space=c(0.25,0.25) ,
        col="red",yaxt="n")

#######################################################################
# End of script
#######################################################################
